### ISSUE TITLE
Profit Items

### ISSUE THREAD

**Issue by Xeroner** [TheAnthonyNL/SteamBot#2]
Hi There @TheAnthonyNL .

Ive got an error while sending profit items, iv'e provided good steamid64 admin account but bot don't sending me profits.

**Comment by TheAnthonyNL** [comment]
it only sends th if there are profit items...

**Comment by Xeroner** [comment]
I know, but not working

**Comment by TheAnthonyNL** [comment]
1: what is your site, 2: was the pot big enough for extra items ???

**Comment by Xeroner** [comment]
1. csbox.pl | 2. Yes

**Comment by TheAnthonyNL** [comment]
if you accept friend invite lol
