### ISSUE TITLE
error bot 

### ISSUE THREAD

**Issue by eliasferreyra** [TheAnthonyNL/SteamBot#31]
inspect img:
http://subefotos.com/ver/?7cd4bee5778354a9e79bb261d60c88e3o.png
 i send offert bot, and error!
solution?

**Comment by Stuffa1991** [comment]
It literally says it in the error, you have to wait 7 days for the escrow ban to be over

**Comment by eliasferreyra** [comment]
7 days after the error continues :S

**Comment by TheAnthonyNL** [comment]
Keep waiting...
