### ISSUE TITLE
Bot crashes when I try to "exec 0 linkauth"

### ISSUE THREAD

**Issue by ICallHax** [TheAnthonyNL/SteamBot#33]
Hello

So I wanted to make a new build of my bot as the previous ones were not working. So I built the bot successfully put in the steam code from my email and signed in successfully. Unfortunately when I do exec 0 link auth it crashes the bot.

Here is a screenshot of the log:
https://gyazo.com/e1e6b10ee94dbbe4ca3e86a98bb513d2

Please help!

**Comment by Robinlemon** [comment]
Uninstall the JSON Module then reinstall It

**Comment by ICallHax** [comment]
[Fixed] @Robinlemon solution worked. Go into your project and uninstall and reinstall the JSON modules and rebuild the project. Thanks for the help!

**Comment by TheAnthonyNL** [comment]
It was written in the guide :(

**Comment by Robinlemon** [comment]
@TheAnthonyNL Ye but n00bs

**Comment by ICallHax** [comment]
@Robinlemon I read it, and I tried it. However it did not work, you recommended it here so I tried it and it worked somehow.

**Comment by Robinlemon** [comment]
@ICallHax alrighty, we should stop commenting
