### ISSUE TITLE
Offer declined, user has not been using mobile authenticator for more then 7 days.

### ISSUE THREAD

**Issue by ICallHax** [TheAnthonyNL/SteamBot#35]
Hello,

So today I dicided to test my bot and send a trade offer from my main account to my bot. Upon confirming my trade offer through the mobile authenticator I saw that the console of the bot say that the user has not had the mobile authenticator for more then 7 days.

What is strange about this is that I have had the mobile authenticator for more then a month and have done many trades prior to sending the trade offer to the bot.

Here is a screenshot of the log https://gyazo.com/1455b882e6c796b4e2b340169917181e

What should I do to fix this. 

PS: I just recently linked the mobile authenticator to the bot. could that be the source of the problem?

**Comment by Xeroner** [comment]
If you link mobile auth to bot you need to wait 7 days man....

**Comment by ICallHax** [comment]
Ok I understand that was sort of my question. But the reason I was asking
is cause it said the user. So I understood it as the person who was sending
the trade offer didn't have the mobile Auth for more then 7 days.

**Comment by TheAnthonyNL** [comment]
User is you, else it would decline the trade ofder saying nickname x has no mobile auth.

**Comment by ICallHax** [comment]
Ok thanks.
