### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by JohnnyGBigg** [TheAnthonyNL/SteamBot#48]
I'm currently getting a problem with the bot. When I use the 'exec 0 linkauth' command, the bot will crash and throw this error:

`Unhandled Exception: System.IO.FileLoadException: COuld not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, CUlture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT:0x80131040)

at SteamAuth.UserLogin.DoLogin()
at SteamBot.Bot.<LinkMobileAuth>b__13() in c:\Users\Me\Desktop\SteamBot-master\SteamBot\Bot.cs:line 796`

and a few more system callback threading errors.

Any help or idea how to fix this?

**Comment by IBeRamen** [comment]
Uninstall Json in the NuGet packages and reinstall it using the latest version. Do this for SteamTrade, ExampleBot and the third solution.

**Comment by JohnnyGBigg** [comment]
My man
