### ISSUE TITLE
SteamGuard Account

### ISSUE THREAD

**Issue by TheRod1990** [TheAnthonyNL/SteamBot#5]
Hey, im a little bit confused about the new SteamGuard Authentification.

When i compile i get the following error on line 130 in the Bot.cs.

public SteamAuth.SteamGuardAccount SteamGuardAccount; 

error CS0246: The type or namespace name `SteamAuth' could not be found. Are you missing an assembly reference?

I have to add the Authcode right? But where?

**Comment by TheRod1990** [comment]
forgot to copy the steamauth directory...can be closed :palm_tree:

**Comment by TheAnthonyNL** [comment]
^^
