### ISSUE TITLE
Problem with authenticate

### ISSUE THREAD

**Issue by Xeroner** [TheAnthonyNL/SteamBot#7]
Hi There @TheAnthonyNL . 
There is a problem after updating bot.

[CSBOX.PL 2015-12-11 21:18:10] INTERFACE: Enter phone number with country code, e.g. +1XXXXXXXXXXX (type "input [index] [number]"):
input 0 +48mynumber
[(System) 2015-12-11 21:18:12] DEBUG: Sending input "+48mynumber" to Bot at index 0
botmgr > [CSBOX.PL 2015-12-11 21:18:13] ERROR: Error adding authenticator: GeneralFailure

**Comment by TheAnthonyNL** [comment]
Try again maybe?

**Comment by Xeroner** [comment]
I was trying something like 15 times....

**Comment by TheAnthonyNL** [comment]
Also i would prefer to add phone number by using the account page of steam.

**Comment by Xeroner** [comment]
It's added :(

**Comment by Xeroner** [comment]
And bot doesn't read it?

**Comment by Xeroner** [comment]
http://scr.hu/9li8/x1nx0

**Comment by TheAnthonyNL** [comment]
Strange ...

**Comment by MilyGosc** [comment]
Had same problem, generaly i suggest to use cloning, and done changes from NOTES, before you make build. After this everything is working properly (for me). And ofc set up number in settings page on steam.

**Comment by Xeroner** [comment]
It's not working... still this same problem...
